	
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("01","01",01,"Economía, Modelo Productivo y Empleo",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0101","01",1,"Hacienda y fiscalidad","01");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010101","01",1,"Marco fiscal y reforma del Sistema de Financiación Autonómico","0101");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010102","02",2,"La necesidad de una revolución fiscal para luchar en contra de la desigualdad y la pobreza","0101");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0102","02",2,"Cambio de modelo productivo","01");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010201","01",1,"Hacia un nuevo modelo productivo","0102");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010202","02",2,"Banca pública: derecho al crédito","0102");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010203","03",3,"Universidad como motor de I+D+i","0102");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010204","04",4,"Turismo y hostelería","0102");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010205","05",5,"Agricultura, ganadería y pesca","0102");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010206","06",6,"Economía azul","0102");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010207","07",7,"Una nueva política de cohesión económica y social","0102");	
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0103","03",3,"Empleo","01");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010301","01",1,"Empleo estable","0103");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010302","02",2,"Formación profesional","0103");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010303","03",3,"Lucha contra la precariedad","0103");
		REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("010304","04",4,"Mejores relaciones laborales","0103");	
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("02","02",02,"Bienes Comunes",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0201","01",1,"Políticas medioambientales y cambio climático","02");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0202","02",2,"Agua","02");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0203","03",3,"Energía","02");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0204","04",4,"Patrimonio natural y biodiversidad","02");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0205","05",5,"Residuos y economía circular","02");	
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("03","03",03,"Transparencia, Anticorrupción, Participación y Democracia",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0301","01",1,"Transparencia","03");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0302","02",2,"Ética y Anticorrupción","03");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0303","03",3,"Participación","03");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0304","04",4,"Más democracia","03");
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("04","04",04,"Servicios Públicos",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0401","01",1,"Empleo público","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0402","02",2,"Sanidad","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0403","03",3,"Educación","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0404","04",4,"Vivienda","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0405","05",5,"Justicia","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0406","06",6,"Servicios sociales ","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0407","07",7,"Dependencia","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0408","08",8,"Deporte","04");	
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0409","09",9,"RTVA y medios de comunicación","04");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0410","10",10,"Infancia, juventud y mayores","04");	
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("05","05",05,"Feminismos, Igualdad y Sexualidades",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0501","01",1,"Feminismos","05");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0502","02",2,"LGTBI","05");
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("06","06",06,"Derechos de los Animales",NULL);
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("07","07",07,"Memoria Histórica y Democrática",NULL);
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("08","08",08,"Cultura Andaluza e Interculturalidad",NULL);
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("09","09",09,"Territorio",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0901","01",1,"Ordenación y gestión del territorio","09");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0902","02",2,"Transporte y movilidad","09");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("0903","03",3,"Urbanismo y ciudades inteligentes","09");
REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("10","10",10,"Derechos Humanos y Civiles, Migraciones, Solidaridad, Cooperación y Pueblo Gitano",NULL);
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("1001","01",1,"Derechos humanos y civiles y migraciones","10");
	REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("1002","02",2,"Solidaridad y cooperación","10");
        REPLACE adelante_programa_categorias (id, codigo, orden, nombre, padre) VALUES ("1003","03",3,"Pueblo gitano","10");